### ISSUE TITLE
Gap on details views

### ISSUE THREAD

**Issue by r2dedios** [RHEcosystemAppEng/cluster-iq-console#49]
On certain detail pages, there is a noticeable blank space that the interface does not dynamically resize in width, as shown in the following image:

![image](https://github.com/user-attachments/assets/3d87ecc7-1ce1-4df3-a9fc-d2f7ded32186)

This is present on:
- [ ] Accounts -> {ACCOUNT} -> Details/Clusters
- [ ] Clusters -> {CLUSTER} -> Details/Servers
- [ ] Servers -> {SERVER} -> Details

Review those pages and fix the dynamic width

**Comment by vbelouso** [comment]
Closed #51
